Cn geneid remap
broadinstitute/depmap_omics pull request #220
Opened 2024-07-25 18:45 UTC by 5im1z

test run results: https://cds.team/taiga/dataset/cn-latest-8bea/15

2024-09-03 19:49 UTC, dpmccabe requested changes

2024-09-03 19:49 UTC, dpmccabe commented on depmapomics/tasks/oncokb_dm/data/oncogene_oncokb_ensg.txt
Do you know why there are some `None` lines? Also, can you add a comment in `constants.py` or elsewhere with instructions on generating this file?

2024-09-03 19:49 UTC, dpmccabe commented on depmapomics/copynumbers.py
> +    mybiomart = mybiomart.drop_duplicates("ensembl_gene_id", keep="first")
can remove (already did above)

2024-09-03 19:49 UTC, dpmccabe commented on depmapomics/copynumbers.py
>      to_rescue = open(rescue_list, "r").read().split("\n")
While we're here: 1) wrap in `with open():` block, 2) use `.splitlines()` instead of `.split()`

2024-09-03 19:49 UTC, dpmccabe commented on depmapomics/dm_omics.py
> +    genes_to_mask = open(masked_gene_list, "r").read().split("\n")
1) wrap in `with open():` block, 2) use `.splitlines()` instead of `.split()`

2024-09-03 21:23 UTC, 5im1z commented on depmapomics/tasks/oncokb_dm/data/oncogene_oncokb_ensg.txt
Ah nice catch! Looks like they just don't have ENSG ids in the mapping table I used. I just dropped them and added comments in [constants.py](https://github.com/broadinstitute/depmap_omics/pull/220/files#diff-fe7369842ee945b25ec2370b06c4bf62c84cf4da70a2e00a41ba07b4b5d5f4b4R342) about how the file is generated

2024-09-04 20:14 UTC, dpmccabe approved these changes
Haven't looked at the results in Taiga. I'll leave that for someone who knows more about how they're supposed to look.

2024-09-09 14:50 UTC, merged