Add rescue reason to maf
broadinstitute/depmap_omics pull request #229
Opened 2024-09-06 14:04 UTC by 5im1z

Poetry updates don't really have anything to do with this feature, just something I had to do to reinstall depmap-omics. Lmk if it's better if I submit a separate PR for that

2024-09-06 15:40 UTC, dpmccabe requested changes

2024-09-06 15:40 UTC, dpmccabe commented on depmapomics/mutations.py
> +        (maf["oncokb_effect"].isin(["Loss-of-function", "Gain-of-function"]))
Should we also allow `Likely Loss-of-function` and `Likely Gain-of-function` values?

2024-09-09 14:58 UTC, qinqian approved these changes

2024-09-09 15:01 UTC, dpmccabe approved these changes

2024-09-09 15:01 UTC, merged