added CCLE SNP Fingerprinting pipeline
broadinstitute/depmap_omics pull request #26
Opened 2021-05-06 21:10 UTC by colganwi

Pipeline updates the LOD matrix on Taiga. We will need to add downstream analysis to this once we determine what analyses are most useful.

2021-05-07 18:07 UTC, jkobject requested changes
I have a couple questions listed in comments.
Also I would advice keeping the data (map files) in the ccle buckets with the rest of the ccle data.

Also I have seen this multi step pipeline to make the snps. Do you plan on updating it later? 
If this is something I might handle in the future, I have a couple questions / requests.

2021-05-07 18:07 UTC, jkobject commented on RNA_CCLE.ipynb
>     "nbconvert_exporter": "python",
can you remove this change from the pull request?

2021-05-07 18:07 UTC, jkobject commented on Fingerprint_pipeline/make_ccle_29k_coding_snps_step2.R
> +# These steps are required for lifting over the map to hg38
could you push a python version of this instead?

How should I call it? what are the inputs? what are the outputs?

2021-05-07 18:07 UTC, jkobject commented on Fingerprint_pipeline/make_ccle_29k_coding_snps_step1.sh
> +CHR="22"
this bash script wont work as is.

maybe can add a for loop across all chromosome, 
also maybe add mkdirs for missing directoriess

2021-05-07 18:07 UTC, jkobject commented on Fingerprint_pipeline/make_ccle_29k_coding_snps_step1.sh
> +CHR="22"
do I need GATK installed? do I need a specific version?

2021-05-07 18:07 UTC, jkobject commented on Fingerprint_pipeline/make_ccle_29k_coding_snps_step1.sh
> +CHR="22"
also I need bcftools, wget, python (any version?)
also this file is not here I think: ~/Data/Fingerprinting/fingerprint_maps/build_fingerprint_maps.py

2021-05-07 18:07 UTC, jkobject commented on Fingerprint_pipeline/make_ccle_29k_coding_snps_step2.R
> +# These steps are required for lifting over the map to hg38
can we push this multi step pipeline into one part?

2021-05-10 19:55 UTC, colganwi commented on Fingerprint_pipeline/conf_fingerprint_bam_with_liftover.json
> +  'fingerprint.run_fingerprint.liftover_chain': '"gs://fc-secure-6b6a3e1a-6fb8-4d30-b0df-a359e6c5d6e6/b37ToHg38.over.chain"',
Sounds good. I'll switch the paths.

2021-05-10 20:05 UTC, jkobject commented on Fingerprint_pipeline/make_ccle_29k_coding_snps_step1.sh
> +CHR="22"
ok let's put it in a folder: Fingerprintin../tasks/ to make differentiate it from non One-Off tasks.

2021-05-12 17:59 UTC, jkobject approved these changes
there is one line that I don't understand otherwise you can merge the pull request! :)

2021-05-12 17:59 UTC, jkobject commented on Fingerprint_pipeline/fingerprint_bam.wdl
> +    gsutil cp "${output_name}.vcf" "${output_dir}/${output_name}.vcf"
hey, you still have this step that is not necessary, except if I am missing something

2021-05-13 17:03 UTC, merged