Simone sandbox
broadinstitute/depmap_omics pull request #45
Opened 2021-09-08 18:27 UTC by 5im1z

made changed according to comments in the prev PR (uncommented certain lines, added back mistakenly removed files, nbstripout'ed notebooks, etc.)

2021-09-08 18:44 UTC, javadnoorb commented
@5im1z can you also resolve the merge conflicts? -thanks

2021-09-08 21:02 UTC, javadnoorb approved these changes
This looks good as far as I can tell

2021-09-10 19:31 UTC, jkobject requested changes
Great, no real changes anymore it seems...

Maybe don't drop the csv and txt files from james_rna, this is the only location where I have that data and this is for a paper around 2 years ago I think this is so that people are able to get it and reproduce results.

2021-09-10 19:31 UTC, jkobject commented on depmapomics/config_prod.py
> +VIRTUAL_FOLDER = "8d9c4c0691154a1f86b1b6e67c3fb683"
already above

2021-09-14 14:10 UTC, merged