Edit readme
broadinstitute/depmap_omics pull request #78
Opened 2022-11-21 16:54 UTC by 5im1z

refactored, removed outdated references, added pipeline subtasks. Didn't make many changed in the QC section since we're in the process of re-implementing the QC process ourselves

2022-12-09 18:04 UTC, qinqian commented on README.md
>    - [QC, Groupding and Uploading](#qc-grouping-uploading)
Groupding->Grouping

2022-12-09 18:32 UTC, qinqian commented on README.md
> +### :warning: Follow instructions [here](documentation/getting_started.md) to set up Terra and obtain access to services required for running the pipeline.
set up -> setup

2023-01-03 02:13 UTC, qinqian commented on README.md
> +### :warning: Follow instructions [here](documentation/getting_started.md) to set up Terra and obtain access to services required for running the pipeline.
The markdown file (documentation/getting_started.md) is missing

2023-01-05 20:36 UTC, qinqian requested changes
Please my review comments for the readme markdown parts. I'll take a look of the .ipynb later.

2023-01-05 20:36 UTC, qinqian commented on README.md
>  * Remove fusions involving mitochondrial chromosomes, or HLA genes, or immunoglobulin genes
is there a reference to cite about these remove decisions

2023-01-05 20:36 UTC, qinqian commented on README.md
>  * Remove fusions with FFPM < 0.05 (STAR-Fusion suggests using 0.1, but looking at the translocation data, this looks like it might be too aggressive)
Is there data to support the FPKM cutoff

2023-01-05 20:36 UTC, qinqian commented on README.md
>  - checkGeneChangeAccrossAll: flag any genes which stay at a similar value across all samples
checkGeneChangeAccrossAll -> checkGeneChangeAcrossAll

2023-01-06 20:43 UTC, 5im1z commented on README.md
> -  - depmap_ccle_data
Just gave you admin access!

2023-01-06 20:45 UTC, 5im1z commented on README.md
> -5. If you need to get access to the data delivered by GP, use the following links:
Can you check again now that you have access to the depmap_ccle_data group?

2023-01-06 20:50 UTC, qinqian commented on README.md
> +- identify new samples by looking at the bam files and compare them with bams we have already onboarded
This will be hopefully addressed next meeting

2023-01-06 20:51 UTC, qinqian commented on README.md
> -5. If you need to get access to the data delivered by GP, use the following links:
Now I have access to all of them. Thanks!

2023-01-06 20:57 UTC, 5im1z commented on documentation/DepMap_processing_pipeline.md
> +  - STAR and RSEM indices are generated using GENCODE's "comprehensive gene annotations" GTF and the GRCh38 reference genome for RNA-seq alignment provided in [GTEx's pipeline](https://github.com/bro
No we recently updated the RNAseq pipeline references to use gencode v38

2023-01-06 20:57 UTC, 5im1z commented on documentation/getting_started.md
> +2. For the mutation pipeline you will also need to request dbGaP access (required for TCGA workflows). *See CCLE/new hiree section on Asana for details*.
Oops the CCLE asana project has been renamed to OMICS. You can find the new hiree section under the OMICS project.

2023-01-06 20:57 UTC, 5im1z commented on documentation/getting_started.md
> +  2. you will need to change some of the variables in the `config_global.py` and `config_prod.py`.
config_prod, config_global, and dm_omics are all on the master branch so it should make more sense after it's been merged. Sorry about the confusion!

2023-01-06 20:57 UTC, 5im1z commented on documentation/getting_started.md
> +  3. you won't be able to run the function conditional on the `isCCLE` boolean. You can however reimplement them to create your own pipeline.
It should only be true if you are running the notebook for DepMap releases (basically only if you are CDS omics)

2023-01-19 19:54 UTC, 5im1z commented on README.md
> +* Mark samples that have more than 1500 segments as QC fails and remove them
I don't think we ever had a reference for them, pretty arbitrary..

2023-01-19 19:59 UTC, 5im1z commented on README.md
> +* Remove chrY segments from lines where their chrY segment count is bigger than 150
Genome version is hg38. what downloading link are you referring to?

2023-01-19 19:59 UTC, 5im1z commented on README.md
> +* Remove genes whose Entrez ID is NaN in BioMart in the gene-level matrices
converting this to an asana task

2023-01-19 20:03 UTC, qinqian commented on README.md
> +* Mark samples that have more than 1500 segments as QC fails and remove them
ok, maybe we just accept it for now.

2023-01-19 20:16 UTC, qinqian approved these changes

2023-01-19 20:16 UTC, qinqian commented on README.md
> +* Remove genes whose Entrez ID is NaN in BioMart in the gene-level matrices
I've just added it into the asana task.

2023-01-19 20:16 UTC, qinqian commented on documentation/DepMap_processing_pipeline.md
> +  - STAR and RSEM indices are generated using GENCODE's "comprehensive gene annotations" GTF and the GRCh38 reference genome for RNA-seq alignment provided in [GTEx's pipeline](https://github.com/bro
ok, we need to add this updates into the document as well.

2023-01-19 20:22 UTC, 5im1z commented on documentation/getting_started.md
> +The current owners of these workspaces should give you access.
I don't think we need to put names on here since it applies to so few people. I updated it to say any DepMap Omics team member can grant access

2023-01-19 20:56 UTC, 5im1z commented on documentation/DepMap_processing_pipeline.md
> +  - STAR and RSEM indices are generated using GENCODE's "comprehensive gene annotations" GTF and the GRCh38 reference genome for RNA-seq alignment provided in [GTEx's pipeline](https://github.com/bro
Our read length is actually 150. A previous ACB generated these indices and I'm not sure if there's a particular reason for using 100...

2023-01-19 20:57 UTC, 5im1z commented on documentation/DepMap_processing_pipeline.md
> +[RNA_aggregate](https://dockstore.org/workflows/github.com/broadinstitute/depmap_omics/RNA_aggregate:master?tab=info) aggregates expression and fusion data files into their respective aggregated file
They are tsv or txt.gz. These are intermediate files though. We pull them from terra and do postprocessing locally and generate csv matrices and dataframes

2023-01-19 22:22 UTC, 5im1z commented on documentation/getting_started.md
> +- In order to use internal-only functions involved in the loading, depmap data post-processing, and uploading, you need to install the [depmap_omics_upload repo](https://github.com/broadinstitute/dep
Here's the repo: https://github.com/broadinstitute/depmap_omics_upload

2023-01-19 22:32 UTC, qinqian approved these changes

2023-01-19 22:34 UTC, qinqian commented
Great jobs! We could merge this PR and close the comment.

2023-01-19 22:35 UTC, merged